In [1]:
import numpy as np

In [2]:
#Creating Array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b=np.array([12,34,"ABHI",True]);b

array(['12', '34', 'ABHI', 'True'], dtype='<U11')

In [6]:
b.dtype

dtype('<U11')

In [7]:
a.dtype

dtype('int32')

In [8]:
a1 = np.array([10,20,30,40]);a1

array([10, 20, 30, 40])

In [9]:
a1.dtype

dtype('int32')

In [10]:
a1.size

4

In [11]:
a1.itemsize

4

In [12]:
a1.ndim

1

In [13]:
#Different ways of creating arrays
np.arange(10,20,3)

array([10, 13, 16, 19])

In [14]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [16]:
a1.shape

(4,)

In [17]:
#Different ways of creating arrays
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [18]:
np.array(np.random.randn(5),dtype='int')

array([ 0,  0,  2,  0, -1])

In [19]:
np.array(np.random.randn(5),dtype='int')

array([ 0, -1, -2,  1,  0])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.array([1,23,4],dtype="float")

array([ 1., 23.,  4.])

In [24]:
#Multidimensional arrays
np.array([[2,4],[8,9]])

array([[2, 4],
       [8, 9]])

In [25]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])