In [1]:
print("Hello World")

Hello World


<ul>
    <li>A</li>
    <li>B</li>
    <li>C</li>

</ul>

# Numpy

In [3]:
import numpy as np

In [3]:
array=np.array([1,2,3,4])

In [4]:
array

array([1, 2, 3, 4])

In [5]:
type(array)

numpy.ndarray

In [6]:
# Array store homogenous data type
array=np.array([1,2,"abhi",True])

In [7]:
print(array)

['1' '2' 'abhi' 'True']


# properties of an array

In [8]:
a1=np.array([10,20,30]);a1

array([10, 20, 30])

In [9]:
a1.ndim

1

In [10]:
a1.dtype

dtype('int32')

In [11]:
a1.shape

(3,)

In [12]:
#count is size
a1.size

3

In [13]:
# itemsize is size of indidual item here 4 byte
a1.itemsize

4

In [14]:
l=[[1,2,3],[4,5,6]];1

1

In [15]:
l[1][2]

6

# Different ways of creating arrays


In [16]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
#how many divisions ie data line divided into 5 divisions
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
np.array(np.random.randn(5),dtype='int')

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.array(np.random.randn(6)*10,dtype="int")

array([ 6, 15,  4,  3,  0,  4])

# Multidimensional arrays


In [24]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
a = np.arange(10,20).reshape(2,5)

In [26]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
a.sum()

145

In [31]:
a.max()

19

In [32]:
a.sum(axis=0)

array([25, 27, 29, 31, 33])

In [33]:
a.min()

10

In [34]:
a.max(axis=1)

array([14, 19])

In [38]:
a=np.arange(20).reshape(2,2,5)

In [39]:
a.sum(axis=0)

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [40]:
a.sum(axis=1)

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33]])

In [41]:
a.sum(axis=2)

array([[10, 35],
       [60, 85]])

In [43]:
###Numpy Functions
a=np.array([1,2,3,1,2,3,4,5,6,7,8,9,8,7,6,5]);a

array([1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 7, 6, 5])

In [46]:
np.mean(a)

4.8125

In [47]:
np.median(a)

5.0

In [48]:
q1=np.quantile(a,.25)

In [49]:
q3=np.quantile(a,0.75)

In [50]:
IQR=q3-q1

In [51]:
IQR

4.25

In [52]:
upper_range=q3+1.5*IQR

In [53]:
upper_range

13.375

In [55]:
lower_range=q1-1.5*IQR;lower_range

-3.625

In [56]:
lower_range

-3.625

# Maths Functions


In [3]:
np.sin(60)

-0.3048106211022167

In [5]:
np.cos(40)

-0.6669380616522619

In [6]:
np.log(1)

0.0

In [9]:
np.log10(10)

1.0

# Reducing Skewness

In [13]:
a = np.array([2,3,4,5,6,7,8,9,4,5,6,7,8,9])

In [14]:
a

array([2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7, 8, 9])

In [15]:
np.mean(a)

5.928571428571429

In [16]:
np.median(a)

6.0

In [17]:
from scipy.stats import skew

In [18]:
skew(a)

-0.17621732641308754

In [23]:
a1 = np.arange(10,16).reshape(3,2)

In [24]:
a1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [25]:
a2=np.arange(16,22).reshape(3,2)

In [26]:
a2

array([[16, 17],
       [18, 19],
       [20, 21]])

In [27]:
np.concatenate([a1,a2])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [28]:
np.concatenate([a1,a2],axis=1)

array([[10, 11, 16, 17],
       [12, 13, 18, 19],
       [14, 15, 20, 21]])

In [30]:
np.unique([1,2,2,3])

array([1, 2, 3])

In [32]:
np.unique([1,1,2,3],return_counts=True)

(array([1, 2, 3]), array([2, 1, 1], dtype=int64))

#  Indexing and Slicing

In [5]:
a = np.arange(10,20).reshape(5,2)

In [35]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [36]:
a[1]

array([12, 13])

In [38]:
a[1][1]

13

In [39]:
a[1,1]

13

In [40]:
a[2:4,]

array([[14, 15],
       [16, 17]])

In [6]:
a[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [7]:
a[2:4,1]

array([15, 17])

In [8]:
a[2,0]

14

In [9]:
a[[1,2]]

array([[12, 13],
       [14, 15]])

In [10]:
a[[0,2],1]

array([11, 15])

# Boolean Indexing

In [11]:
a[[0,2],0]

array([10, 14])

In [12]:
a>12

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [13]:
a[a>12]

array([13, 14, 15, 16, 17, 18, 19])

In [14]:
a[a%2==0]

array([10, 12, 14, 16, 18])

#Vectorization 
means it makes scalar into vector form

In [16]:
a = np.array([1,2,3,4,5,6,7,9,7]);a

array([1, 2, 3, 4, 5, 6, 7, 9, 7])

In [17]:
s=10

In [18]:
a+s

array([11, 12, 13, 14, 15, 16, 17, 19, 17])

In [19]:
a*10

array([10, 20, 30, 40, 50, 60, 70, 90, 70])

In [20]:
np.array([10,20,30])*12

array([120, 240, 360])

#Broadcasting means makes scalar into  matrix form

In [26]:
a1 = np.array([[5,6],[8,9]])

In [27]:
a2 = np.array([2,3])

In [28]:
a2

array([2, 3])

In [29]:
a1+a2

array([[ 7,  9],
       [10, 12]])

#Cross product and Dot product

In [30]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [31]:
a1

array([[1, 2],
       [3, 4]])

In [32]:
a2

array([[5, 6],
       [7, 8]])

In [33]:
#cross product
a1*a2

array([[ 5, 12],
       [21, 32]])

In [34]:
#dot product
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])